10 ' PRELUDE from FINAL FANTASY -------
20 '
30 CLS :PRINT "PRELUDE from FINAL FANTASY"
40 PLAY *,&300:PLAY "T82L16O2"
50 A$="CDEG>CDEG>CDEG>CDEG>C<GEDC<GEDC<GEDC<GED<"
60 B$="AB>CEAB>CEAB>CEAB>CEAEC<BAEC<BAEC<BAEC<B>"
70 PLAY A$+B$+A$+B$
80 PLAY "<A>CFGA>CFGA>CFGA>CFGAGFC<AGFC<AGFC<AGFC<"
90 PLAY "B>DGAB>DGAB>DGAB>DGABAGD<BAGD<BAGD<BAGD<"
100 PLAY "G#>CD#GG#>CD#GG#>CD#GG#>CD#GG#GD#C<G#GD#C<G#GD#C<G#GD#C<"
110 PLAY "A#>DFAA#>DFAA#>DFAA#>DFAA#AFD<A#AFD<A#AFD<A#AFD"
120 GOTO 70
